version: '3.4'

services:

  testdatabase:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Pass@word
  
  integrationtests:
    image: integrationtests:1.0.0   
    build:
      context: .
      dockerfile: ./IntegrationTests.Dockerfile       
    depends_on:
      - testdatabase