version: '3.4'

services:

  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Pass@word    
  
  productstore-api:
    image: productstore.api:1.0.0
    environment:
     - ASPNETCORE_ENVIRONMENT=Production
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"    
    depends_on:
      - database